### ISSUE TITLE
Crash gesture settings (ArrayIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by ShevT** [crdroidandroid/android_packages_apps_LineageParts#10]
```
02-25 19:07:05.392  8643  8643 E AndroidRuntime: FATAL EXCEPTION: main
02-25 19:07:05.392  8643  8643 E AndroidRuntime: Process: org.lineageos.lineageparts, PID: 8643
02-25 19:07:05.392  8643  8643 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at org.lineageos.lineageparts.gestures.TouchscreenGestureSettings.buildActionList(TouchscreenGestureSettings.java:193)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at org.lineageos.lineageparts.gestures.TouchscreenGestureSettings.sendUpdateBroadcast(TouchscreenGestureSettings.java:207)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at org.lineageos.lineageparts.gestures.TouchscreenGestureSettings.access$200(TouchscreenGestureSettings.java:43)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at org.lineageos.lineageparts.gestures.TouchscreenGestureSettings$TouchscreenGesturePreference.persistString(TouchscreenGestureSettings.java:116)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.preference.ListPreference.setValue(ListPreference.java:190)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.preference.ListPreference.onSetInitialValue(ListPreference.java:255)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.preference.Preference.onSetInitialValue(Preference.java:1616)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.preference.Preference.dispatchSetInitialValue(Preference.java:1589)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1313)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1328)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.preference.PreferenceGroup.addPreference(PreferenceGroup.java:250)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at org.lineageos.lineageparts.gestures.TouchscreenGestureSettings.initTouchscreenGestures(TouchscreenGestureSettings.java:71)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at org.lineageos.lineageparts.gestures.TouchscreenGestureSettings.onCreate(TouchscreenGestureSettings.java:62)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2939)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:451)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2209)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2120)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2022)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3244)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3178)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:473)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1461)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:8075)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3660)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7839)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-25 19:07:05.392  8643  8643 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by ShevT** [comment]
Reproduce:
1) Open System settings -> System -> Gestures
2) Press "Touchscreen gestures"

**Comment by gwolf2u** [comment]
fixed in https://github.com/crdroidandroid/android_kernel_oneplus_sm8150/commit/9b457a60cbc021df774844958a19e207891abdcf
